apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: p8t7mcykc-go 
  janus-idp.io/tekton: p8t7mcykc-go
  backstage.io/kubernetes-id: p8t7mcykc-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p8t7mcykc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml