apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: p8t7mcykc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: p8t7mcykc-go 
  name: p8t7mcykc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: p8t7mcykc-go 
